### PR TITLE
Major refactor after week0

### PR DESCRIPTION
**Pull request by KenwoodFox**
Aims to solve multiple missing features
 - [ ] Difflock
 - [ ] Hold Position
 - [ ] Auto balance ?
 - [ ] Arm presets
 - [ ] Simple auto

### CODE REVIEW

**Comment by KenwoodFox** [comment]
image

**Comment by KenwoodFox** [comment]
I am also requesting a review from @dublUayaychtee because i modified some `dashboard/` stuff

**Comment by Kredcool** [comment]
I am currently working on autonomous driving backwards but I have found this issue when running curry auto.
```********** Robot program startup complete **********
navX-Sensor Connected.
navX-Sensor Board Type 33 (unknown)
navX-Sensor firmware version 3.1
navX-Sensor startup initialization and startup calibration complete.
navX-Sensor onboard startup calibration complete.
navX-Sensor Yaw angle auto-reset to 0.0 due to startup calibration.
ERROR:your.robot:Unhandled exception
Traceback (most recent call last):
  File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
    self.robot.startCompetition()
  File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
    self.targElev + (self.elevatorFineControl() * 15),
TypeError: 'int' object is not callable
17:21:07:843 ERROR   : your.robot          : Unhandled exception
Traceback (most recent call last):
  File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
    self.robot.startCompetition()
  File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
    self.targElev + (self.elevatorFineControl() * 15),
TypeError: 'int' object is not callable
ERROR:robotpy:The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
Traceback (most recent call last):
  File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 75, in start
    return self._start(robot_cls)
  File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
    self.robot.startCompetition()
  File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
    self.targElev + (self.elevatorFineControl() * 15),
TypeError: 'int' object is not callable
17:21:07:843 ERROR   : robotpy             : The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
Traceback (most recent call last):
  File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 75, in start
    return self._start(robot_cls)
  File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
    self.robot.startCompetition()
  File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
    self.targElev + (self.elevatorFineControl() * 15),
TypeError: 'int' object is not callable
Warning at Main: Warning: Watchdog not fed within 0.020000s
	at <no python frames>
	at  + 0x39e4f [0x7f70b076de4f]
	at  + 0x155e21 [0x7f70b1715e21]
	at _PyObject_MakeTpCall + 0x2ab [0x7f70b170f4eb]
	at _PyEval_EvalFrameDefault + 0x5154 [0x7f70b170a2e4]
	at _PyFunction_Vectorcall + 0x79 [0x7f70b17162d9]
	at  + 0xc5119 [0x7f70b07f9119]
	at wpi::GetStackTrace[abi:cxx11](int) + 0x26 [0x7f70b0b06c46]
	at frc::ReportErrorV(int, char const*, int, char const*, fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >) + 0x1d8 [0x7f70af8245f8]
	at frc::Watchdog::Impl::Main() + 0x2cf [0x7f70af846bff]
	at  + 0xd72c3 [0x7f70b092f2c3]
	at  + 0x85bb5 [0x7f70b145ebb5]
	at  + 0x107d90 [0x7f70b14e0d90]


CommandScheduler loop time overrun.
make: *** [Makefile:28: sim] Error 1```

**Comment by KenwoodFox** [comment]
> I am currently working on autonomous driving backwards but I have found this issue when running curry auto.
> 
> ```
> navX-Sensor Connected.
> navX-Sensor Board Type 33 (unknown)
> navX-Sensor firmware version 3.1
> navX-Sensor startup initialization and startup calibration complete.
> navX-Sensor onboard startup calibration complete.
> navX-Sensor Yaw angle auto-reset to 0.0 due to startup calibration.
> ERROR:your.robot:Unhandled exception
> Traceback (most recent call last):
>   File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
>     self.robot.startCompetition()
>   File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
>     self.targElev + (self.elevatorFineControl() * 15),
> TypeError: 'int' object is not callable
> 17:21:07:843 ERROR   : your.robot          : Unhandled exception
> Traceback (most recent call last):
>   File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
>     self.robot.startCompetition()
>   File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
>     self.targElev + (self.elevatorFineControl() * 15),
> TypeError: 'int' object is not callable
> ERROR:robotpy:The robot program quit unexpectedly. This is usually due to a code error.
> The above stacktrace can help determine where the error occurred.
> Traceback (most recent call last):
>   File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 75, in start
>     return self._start(robot_cls)
>   File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
>     self.robot.startCompetition()
>   File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
>     self.targElev + (self.elevatorFineControl() * 15),
> TypeError: 'int' object is not callable
> 17:21:07:843 ERROR   : robotpy             : The robot program quit unexpectedly. This is usually due to a code error.
> The above stacktrace can help determine where the error occurred.
> Traceback (most recent call last):
>   File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 75, in start
>     return self._start(robot_cls)
>   File "/home/kredcool/.local/share/virtualenvs/rio-8nlATpwf/lib/python3.10/site-packages/wpilib/_impl/start.py", line 163, in _start
>     self.robot.startCompetition()
>   File "/home/kredcool/git/1721-ChargedUp/rio/commands/presetArm.py", line 50, in execute
>     self.targElev + (self.elevatorFineControl() * 15),
> TypeError: 'int' object is not callable
> Warning at Main: Warning: Watchdog not fed within 0.020000s
> 	at <no python frames>
> 	at  + 0x39e4f [0x7f70b076de4f]
> 	at  + 0x155e21 [0x7f70b1715e21]
> 	at _PyObject_MakeTpCall + 0x2ab [0x7f70b170f4eb]
> 	at _PyEval_EvalFrameDefault + 0x5154 [0x7f70b170a2e4]
> 	at _PyFunction_Vectorcall + 0x79 [0x7f70b17162d9]
> 	at  + 0xc5119 [0x7f70b07f9119]
> 	at wpi::GetStackTrace[abi:cxx11](int) + 0x26 [0x7f70b0b06c46]
> 	at frc::ReportErrorV(int, char const*, int, char const*, fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >) + 0x1d8 [0x7f70af8245f8]
> 	at frc::Watchdog::Impl::Main() + 0x2cf [0x7f70af846bff]
> 	at  + 0xd72c3 [0x7f70b092f2c3]
> 	at  + 0x85bb5 [0x7f70b145ebb5]
> 	at  + 0x107d90 [0x7f70b14e0d90]
> 
> 
> CommandScheduler loop time overrun.
> make: *** [Makefile:28: sim] Error 1```
> ```

Yes this is because you cannot callable on an int. Why did you guys come onto my branch lol and not make your own XD

**Pull request merged**
